vich_uploader:
    db_driver: orm

    mappings:
        company_image:
            uri_prefix: /images/uploads/company
            upload_destination: '%kernel.project_dir%/public/images/uploads/company'
        
        program_file:
            uri_prefix: /images/uploads/eventProgram
            upload_destination: '%kernel.project_dir%/public/images/uploads/eventProgram'

        partner-logo:
            uri_prefix: /images/uploads/partnerLogo
            upload_destination: '%kernel.project_dir%/public/images/uploads/partnerLogo'

        member_photo:
            uri_prefix: /images/uploads/memberPhoto
            upload_destination: '%kernel.project_dir%/public/images/uploads/memberPhoto'

